version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3002:3000'
      - '3035:3035'
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      LC_CTYPE: ja_JP.UTF-8
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
      DATABASE_USER: postgres
      DATABASE_PASSWORD: shoukaigame_password
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    links:
      - db
    volumes:
      - .:/shoukaigame
      - /shoukaigame/node_modules
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:11.1-alpine
    ports:
      - '3307:3306'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=shoukaigame_password"
