# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/shoukaigame_app
  docker:
    # specify the version you desire here
    - image: circleci/ruby:2.6.3-node-browsers-legacy
      environment:
        RAILS_ENV: test
        TZ: /usr/share/zoneinfo/Asia/Tokyo
        BUNDLE_PATH: vendor/bundle
        BUNDLER_VERSION: 1.17.2
    - image: postgres:11.1-alpine
      environment:
        - POSTGRES_USER: postgres
        - POSTGRES_PASSWORD: shoukaigame_password
        - PGDATA: /dev/shm/pgdata/data
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: gem install bundler -v 1.17.2
      - run: bundle install
      - persist_to_workspace:
          root: ~/shoukaigame_app
          paths:
            - ./*
  # RuboCop check!!
  code_analyze:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/shoukaigame_app
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3
      - run:
          name: Run Rubocop
          command: bundle exec rubocop --parallel
  rspec:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/shoukaigame_app
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3
      # Database setup
      - run:
          name: Database setup
          command: |
            bundle exec rake db:create RAILS_ENV=test
            bundle exec rake db:schema:load RAILS_ENV=test
      - run:
          name: Run RSpec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - code_analyze:
          requires:
            - build
      - rspec:
          requires:
            - build
